/*!
 * 
 *             description:  结合Localstorage和SessionStorage的数据缓存方案
 *             author: Yonyou FED Team
 *             date: 2018-05-07
 *             version: V0.0.2
 *             file: localStorage.js
 *         
 */
!function(e,t){if("object"==typeof exports&&"object"==typeof module)module.exports=t();else if("function"==typeof define&&define.amd)define([],t);else{var r=t();for(var i in r)("object"==typeof exports?exports:e)[i]=r[i]}}(window,function(){return function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.m=e,r.c=t,r.d=function(e,t,i){r.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:i})},r.r=function(e){Object.defineProperty(e,"__esModule",{value:!0})},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=2)}([,function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.serialize=function(e){return JSON.stringify(e)},t.deserialize=function(e){if("string"!=typeof e)return;try{return JSON.parse(e)}catch(t){return e||void 0}}},function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var i=r(1),n={version:"0.0.4",storage:window.localStorage,maxSize:0,usedSize:0},o={set:function(e,t){if(!this.disabled)return void 0===t?this.remove(e):(this.storage.setItem(e,(0,i.serialize)(t)),t)},get:function(e,t){if(this.disabled)return t;var r=(0,i.deserialize)(this.storage.getItem(e));return void 0===r?t:r},has:function(e){return void 0!==this.get(e)},remove:function(e){this.disabled||this.storage.removeItem(e)},clear:function(){this.disabled||this.storage.clear()},getAll:function(){if(this.disabled)return null;var e={};return this.forEach(function(t,r){e[t]=r}),e},each:function(e){if(!this.disabled)for(var t=0;t<this.storage.length;t++){var r=this.storage.key(t);e(r,this.get(r))}},getUsed:function(e){var t=0;for(var r in this.storage)this.storage.hasOwnProperty(r)&&(t+=this.get(r).length);return this.usedSize=(t/1024).toFixed(2),e&&e(this.usedSize),this.usedSize},getMaxLength:function(){var e="0123456789",t=this;!function t(r){10240!=(r+=r).length?t(r):e=r}(e);var r=e,i=setInterval(function(){r+=e;try{t.remove("test"),t.set("test",r)}catch(e){t.maxSize=(r.length/1024).toFixed(2),clearInterval(i)}},.05);return this.maxSize},getRest:function(){return this.maxSize-this.usedSize}};Object.assign(n,o);try{n.storage||alert("浏览器不支持localStorage");var s="__tinperStorageJS__";n.set(s,s),n.get(s)!==s&&(n.disabled=!0,console.log("存储量满，无法操作")),n.remove(s)}catch(e){n.disabled=!0,"QuotaExceededError"==e.name&&console.log("超出本地存储限额！")}window.localStore=n,t.default=n}])});